################################# Default configuration ###################
baseURL = "https://www.cedna.ca/"
theme = "cedna.github.io"
themesDir = "../.."
title = "Cedna"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ['Fr']
#relativeURLs = true

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "À propos"
pre = "#"
url = "about"
weight = 1

# [[Languages.en.menu.main]]
# name = "Services"
# pre = "#"
# url = "services"
# weight = 2

#[[Languages.en.menu.main]]
#name = "portefeuille"
#pre = "#"
#url = "portfolio"
#weight = 3

# [[Languages.en.menu.main]]
# name = "tarification"
# pre = "#"
# url = "pricing"
# weight = 5

[[Languages.en.menu.main]]
name = "Articles"
pre = "#"
url = "blog"
weight = 4

[[Languages.en.menu.main]]
name = "Équipe"
pre = "#"
url = "team"
weight = 6

[[Languages.en.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 7

# [[Languages.en.menu.main]]
# name = "themefisher"
# pre = ""
# url = "https://themefisher.com/"
# weight = 8

################### French Navigation ########################
[[Languages.fr.menu.main]]
name = "À propos"
pre = "#"
url = "about"
weight = 1

# [[Languages.fr.menu.main]]
# name = "un service"
# pre = "#"
# url = "services"
# weight = 2

# [[Languages.fr.menu.main]]
# name = "portefeuille"
# pre = "#"
# url = "portfolio"
# weight = 3

# [[Languages.fr.menu.main]]
# name = "tarification"
# pre = "#"
# url = "pricing"
# weight = 5

[[Languages.fr.menu.main]]
name = "Articles"
pre = "#"
url = "blog"
weight = 4

[[Languages.fr.menu.main]]
name = "Équipe"
pre = "#"
url = "team"
weight = 6

[[Languages.fr.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 7

# [[Languages.fr.menu.main]]
# name = "themefisher"
# pre = ""
# url = "https://themefisher.com/"
# weight = 8

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
author = "Themefisher"
description = "Comité sur les Enjeux du Développement Numérique et Algorithmique (CEDNA)"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/CEDNA-101966855218103" 

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/cedna_ca/?hl=fr" 

#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#" 

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCAlWpiXHPqsqCTYtYDZyBsA" 

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/cednamtl/" 

#[[params.social]]
#icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
#link = "#" 

#[[params.social]]
#icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
#link = "#" 

################################ France Language ########################
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2021 Designed by Themefisher & Developed by Gethugothemes"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 1

################################ English Language ########################
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 Designed by Themefisher & Developed by Gethugothemes"
home = "Accueil"
languageCode = "en-us"
languageName = "En"
weight = 2